# Generated by Django 5.0.3 on 2024-03-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
