# Generated by Django 5.0.3 on 2024-03-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0002_alter_participant_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingmeeting',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
